name: FJB
favicon: null
layout_spectrum: 0.6208143585827202
typography_spectrum: 0.13596983649767935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.493628968950361
  lightness: 0.9895331570878625
  saturation: 0.8644597972743213
  rhythmicContrast: 0.48362448369152844
purpose: []
